### PR TITLE
Updated to Selenium 3.4.0

### PR DESCRIPTION
**Pull request by kvalev**

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Thank you for sending the commit. I've already updated the version https://github.com/arquillian/arquillian-selenium-bom/commit/6398809e87231ffb9cfa6ea55f19b6ef755a8030 and released it. I just forgot to send the commits

**Comment by kvalev** [comment]
@MatousJobanek Do you plan on releasing it to [maven central](https://mvnrepository.com/artifact/org.jboss.arquillian.selenium/selenium-bom)? The latest version there is still the 3.3.1.

**Comment by MatousJobanek** [comment]
I checked it on Friday and it was there already: http://search.maven.org/#search|ga|1|selenium-bom
I think that mvnrepository.com is just a 3rd party provider (but I can be wrong) of the content and it could have taken some time to sync the index...

**Comment by kvalev** [comment]
Oh, my bad - I must have overlooked it. Thank you!

**Pull request closed without merging**
